# Generated by Django 4.0.1 on 2022-02-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='company',
            new_name='shop',
        ),
    ]
